### ISSUE TITLE
Polyquad fails to build with Eigen 3

### ISSUE THREAD

**Issue by spraetor** [PyFR/Polyquad#1]
When building polyquad with eigen 3 there are some problems: (I use Eigen version 3.3.3)
- in base.hpp:220ff: the temporal storage of `pts.array()` and `out.array()` causes a compiler error. Resolution: call `middleRows<N>(i)` directly on `pts.array()`:

```c++
derived.eval_orthob_block(pts.array().template middleRows<16>(i),
                          out.array().template middleCols<16>(i));
```

- when compiling with mpreal, eigen has some bugs:
  - mpreal changed its definition of `std::numeric_limits`
  - in the algorithm *LevenbergMarquardt* some values of `std::numeric_limits` are used, that are not provided. Resolution: Eigen3 must be patched
[eigen.patch.txt](https://github.com/vincentlab/Polyquad/files/868193/eigen.patch.txt)
  - I will open an issue in the Eigen3 repository

**Comment by FreddieWitherden** [comment]
Thank you for this report.  Please submit a pull request with the relevant changes to base.hpp and I'll get that merged.

The Eigen developers are usually quite responsive when it comes to fixing issues regarding mpreal, especially if a patch is available.

**Comment by spraetor** [comment]
Finally, figured out what is the actual source of the error in a minimal example:

```c++
using Matrix = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>;
Matrix const m(10,10);
auto a = m.array();
auto r = a.row(1); // error: invalid conversion from `const double*` to `double*`
```

If I change `auto a = ...` to `auto const a = ...` all is fine. This seems to be a problem in Eigen. I will report this there, when I get the Bugzilla account activated.

**Comment by FreddieWitherden** [comment]
Can you confirm if this issue is now resolved?
