### ISSUE TITLE
Compilation takes extraordinary amounts of memory

### ISSUE THREAD

**Issue by drwells** [PyFR/Polyquad#4]
I'd like to use this program to generate some simplex quadrature rules. However, AFAICT from running `/usr/bin/time -v`, compilation on master (with just `-O2`) takes more than four hours and requires more than 256GB of memory. I'm using boost 1.70 and I'm not using MPI.

Is this a (very odd) bug due to me not using MPI, or are these large values expected?

Edit: clarification: I wrote "more than" because I don't have access to a system with more memory - the job was killed at that point.

**Comment by FreddieWitherden** [comment]
This is due to a known and reported bug with GCC; see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95264  Switching to a recent version of clang will resolve this issue.

**Comment by drwells** [comment]
Yup, things compile just fine with clang. Thanks!
